name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push docker
        uses: docker/build-push-action@v1
        with:
          dockerfile:  ../Dockerfile
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: riteshshrv/sqljobber
          tags: latest
